# Generated by Django 6.0.4 on 2026-04-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rwgps_access_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='rwgps_user_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
